# Análise Exploratória dos dados
Limpeza
Transformação
Normalização

## Libs utilizadas na exploração dos dados

In [2]:
import pandas as pd
from pathlib import Path

## Definição do diretório onde está a tabela bruta e onde sera adicionada a tabela transformada

In [3]:
BASE_DIR = Path().resolve().parent
INPUT_PATH = BASE_DIR / "data" / "output" / "precos_combustivel_bruto.parquet"
OUTPUT_PATH = BASE_DIR / "data" / "output" / "precos_combustivel_transformado.parquet"

## Define os replaces dos nomes dos campos para melhor legibilidade
Antigo_Nome : Novo_Nome

In [43]:
NEW_NAME_OF_COLUMNS = {
    "Regiao - Sigla": "Regiao",
    "Estado - Sigla": "Estado",
    "Municipio": "Cidade",
    "Revenda": "Revendedor",
    "CNPJ da Revenda": "CNPJ do Revendedor",
    "Produto": "Tipo de Combustível",
    "Bandeira": "Fornecedor"
}

## Leitura do arquivo e informações iniciais para base da análise

In [50]:
df = pd.read_parquet(INPUT_PATH)
df.info()
df.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04431113000100,AVENIDA CAXANGA,126,None,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",None,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,05297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",None,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,02448248000145,SITIO SAO JOSE,SN,None,SEDE,44600-000,DIESEL,01/07/2025,"6,9",None,R$ / litro,ALE
3,NE,BA,ITAMARAJU,CODEPEL -COMERCIO DE DERIVADOS DE PETROLEO LTDA,05696709000197,AVENIDA PERIMENRAL,348,TERREO,CENTRO,45836-000,DIESEL,01/07/2025,"5,99",None,R$ / litro,BRANCA
4,NE,BA,ITAMARAJU,BENTIVI DERIVADOS DE PETROLEO LTDA,13683818000106,RODOVIA BR 101,S/N,KM 808,SEDE,45836-000,DIESEL,01/07/2025,"5,92",None,R$ / litro,IPIRANGA

## Limpeza básica nos dados ajustando nome das colunas, removendo uma coluna desnecessária e adicionando tipagem as dados que forem necessários.

In [52]:
df.rename(columns=NEW_NAME_OF_COLUMNS, inplace=True)
df.drop('Valor de Compra', axis=1, inplace=True)
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.').astype('float')
df['Data da Coleta'] = pd.to_datetime(df['Data da Coleta'], format='%d/%m/%Y', errors='coerce')
df = df[df['Data da Coleta'] != 'NaT']
df.head(5)

,Regiao,Estado,Cidade,Revendedor,CNPJ do Revendedor,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Tipo de Combustível,Data da Coleta,Valor de Venda,Unidade de Medida,Fornecedor
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04431113000100,AVENIDA CAXANGA,126,None,PEDRA VELHA,57480-000,DIESEL,01/07/2025,6.69,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,05297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,6.33,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,02448248000145,SITIO SAO JOSE,SN,None,SEDE,44600-000,DIESEL,01/07/2025,6.90,R$ / litro,ALE
3,NE,BA,ITAMARAJU,CODEPEL -COMERCIO DE DERIVADOS DE PETROLEO LTDA,05696709000197,AVENIDA PERIMENRAL,348,TERREO,CENTRO,45836-000,DIESEL,01/07/2025,5.99,R$ / litro,BRANCA
4,NE,BA,ITAMARAJU,BENTIVI DERIVADOS DE PETROLEO LTDA,13683818000106,RODOVIA BR 101,S/N,KM 808,SEDE,45836-000,DIESEL,01/07/2025,5.92,R$ / litro,IPIRANGA

## Identificando quantidade de nulos para limpeza identificando onde pode ser nulo e onde não pode ser nulo

In [57]:
df.isna().sum()

Regiao                   9114
Estado                   9114
Cidade                   9114
Revendedor               9114
CNPJ do Revendedor       9114
Nome da Rua              9114
Numero Rua               9196
Complemento            630409
Bairro                  10638
Cep                      9114
Tipo de Combustível      9114
Data da Coleta           9114
Valor de Venda           9114
Unidade de Medida        9114
Fornecedor               9114
dtype: int64

In [61]:
df.dropna(subset=['Tipo de Combustível', 'Revendedor', 'CNPJ do Revendedor', 'Fornecedor', 'Valor de Venda', 'Data da Coleta'], inplace=True)
df.isna().sum()

Regiao                      0
Estado                      0
Cidade                      0
Revendedor                  0
CNPJ do Revendedor          0
Nome da Rua                 0
Numero Rua                 82
Complemento            621295
Bairro                   1524
Cep                         0
Tipo de Combustível         0
Data da Coleta              0
Valor de Venda              0
Unidade de Medida           0
Fornecedor                  0
dtype: int64